spring:
  datasource:
    url: jdbc:mysql://localhost:3306/antonio_prova
    username: root
    password: password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create

  mail:
    host: smtp.gmail.com
    port: 587
    username: axelfiumano@gmail.com
    password: CiaoAntonioComeStaviNel1987
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      fail-on-empty-beans: false